const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
    launchGame: (options) => ipcRenderer.send('launch-game', options),
    getVersions: () => ipcRenderer.invoke('get-versions'),
    browseFile: () => ipcRenderer.invoke('browse-file'),
    loginMicrosoft: () => ipcRenderer.invoke('login-microsoft'),
    stopLaunch: () => ipcRenderer.invoke('stop-launch'),
    addMod: (params) => ipcRenderer.invoke('add-mod', params),
    importModpack: (params) => ipcRenderer.invoke('import-modpack', params),
    downloadModpackUrl: (params) => ipcRenderer.invoke('download-modpack-url', params),
    getMods: (params) => ipcRenderer.invoke('get-mods', params),
    removeMod: (params) => ipcRenderer.invoke('remove-mod', params),
    openFolder: (params) => ipcRenderer.invoke('open-folder', params),
    modrinthSearch: (params) => ipcRenderer.invoke('modrinth-search', params),
    modrinthBrowse: (params) => ipcRenderer.invoke('modrinth-browse', params),
    modrinthInstall: (params) => ipcRenderer.invoke('modrinth-install', params),
    modrinthProjectVersions: (params) => ipcRenderer.invoke('modrinth-project-versions', params),
    importMrpackLocal: (params) => ipcRenderer.invoke('import-mrpack-local', params),
    applyOfflineSkin: (params) => ipcRenderer.invoke('apply-offline-skin', params),
    downloadCatalogSkin: (params) => ipcRenderer.invoke('download-catalog-skin', params),
    runOptifineInstaller: (params) => ipcRenderer.invoke('run-optifine-installer', params),
    modrinthListModpacks: () => ipcRenderer.invoke('modrinth-list-modpacks'),
    enableAuthlibInjector: (params) => ipcRenderer.invoke('enable-authlib-injector', params),
    getProfiles: () => ipcRenderer.invoke('get-profiles'),
    saveProfile: (profile) => ipcRenderer.invoke('save-profile', profile),
    deleteProfile: (id) => ipcRenderer.invoke('delete-profile', id),
    enableCustomSkinMod: (params) => ipcRenderer.invoke('enable-custom-skin-mod', params),
    getSkins: (params) => ipcRenderer.invoke('get-skins', params),
    removeSkin: (params) => ipcRenderer.invoke('remove-skin', params),
    hudGetConfig: (params) => ipcRenderer.invoke('hud-get-config', params),
    hudSaveConfig: (params) => ipcRenderer.invoke('hud-save-config', params),
    quickConnect: (params) => ipcRenderer.invoke('quick-connect', params),
    installVoiceMod: (params) => ipcRenderer.invoke('install-voice-mod', params),
    getInstalledContent: (params) => ipcRenderer.invoke('get-installed-content', params),
    deleteInstance: (name) => ipcRenderer.invoke('delete-instance', name),
    deleteContent: (params) => ipcRenderer.invoke('delete-content', params),
    copyConfigFromFolder: (params) => ipcRenderer.invoke('copy-config-from-folder', params),
    windowMinimize: () => ipcRenderer.invoke('window-minimize'),
    windowToggleMaximize: () => ipcRenderer.invoke('window-toggle-maximize'),
    windowClose: () => ipcRenderer.invoke('window-close'),
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
    checkJavaInstalled: () => ipcRenderer.invoke('check-java-installed'),
    autoInstallJava: (params) => ipcRenderer.invoke('auto-install-java', params),
    onProgress: (callback) => ipcRenderer.on('progress', (event, data) => callback(data)),
    onConsoleLog: (callback) => ipcRenderer.on('console-log', (event, data) => callback(data)),
    onLaunchError: (callback) => ipcRenderer.on('launch-error', (event, msg) => callback(msg)),
    onLaunchStatus: (callback) => ipcRenderer.on('launch-status', (event, status) => callback(status)),
    onAutoInstallJavaPrompt: (callback) => ipcRenderer.on('auto-install-java-prompt', (event, data) => callback(data)),
    onJavaInstallProgress: (cb) => ipcRenderer.on('java-install-progress', (e, data) => cb(data)),
    onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (e, info) => cb(info)),
    onUpdateNotAvailable: (cb) => ipcRenderer.on('update-not-available', () => cb()),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (e, info) => cb(info)),
    onUpdateError: (cb) => ipcRenderer.on('update-error', (e, msg) => cb(msg)),
    onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (e, data) => cb(data))
});
